### ISSUE TITLE
Explanation about get_closest_obstacle_distance

### ISSUE THREAD

**Issue by krokomon** [DakotaNelson/particle-filter#5]
Hey there,

I have more of a question than an issue. I have been looking various particle filters implementation and yours is the only one including a get_closest_obstacle_distance function. Since I have not seen such a step in any algorithm, I would like to ask the reason why you are using it. Perhaps I am missing a detail.

Thanks in advance!

**Comment by DakotaNelson** [comment]
Hello!

I haven't looked at this code in a long, long time, but here's my understanding of it:

Essentially, we're taking each individual scan from the robot, and measuring how well it fits each particle. See this snippet here:

https://github.com/DakotaNelson/particle-filter/blob/8172f298714cc0c503833261914ea8945b2410d4/scripts/pf.py#L209-L214

What it's doing is taking a scan, and then iterating through each particle to determine whether that scan fits the particle well. We're only using scan _distance_, so that means that we:

1. Take each scan, and transform it to originate at the particle
2. Find the closest obstacle to the particle
3. Compare the scan's distance to the distance to the closest obstacle
4. Assign a probability to the particle depending on how well the measurement from the scan fits the distance to the closest obstacle

This was a college project, so I wouldn't expect too terribly much from this code - but hopefully that at least explains the thinking behind it, and to some extent at least what it's trying to do (I'm not sure if it actually accomplishes it!).
